apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mdyaipay-infra

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus/prometheus.yml
  - name: prometheus-rules
    files:
      - prometheus/rules/ratelimit-recording-rules.yaml
      - prometheus/rules/ratelimit-alerts.yaml
  - name: grafana-dashboard-ratelimit
    files:
      - grafana/dashboards/ratelimit-gateway.json

resources:
  - grafana/provisioning-datasources.yaml
  - grafana/provisioning-dashboards.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - prometheus/pvc.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/pvc.yaml
