apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: mdyaipay
    app.kubernetes.io/component: infra
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi
