apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: mdyaipay
    app.kubernetes.io/component: infra
  annotations:
    mdyaipay.dev/exposure: docker-desktop-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: http
  selector:
    app.kubernetes.io/name: prometheus
